### ISSUE TITLE
0.0.1.1安装失败

### ISSUE THREAD

**Issue by gn1394594329** [uiharuayako/PantsPlugins#1]
0.0.1.1版本提示安装失败，0.0.1.0加入dc选项显示过期，readme的dc连结也是过期的

**Comment by uiharuayako** [comment]
已更新Readme的dc邀请链接，可以来dc发一下安装日志吗

**Comment by gn1394594329** [comment]
阿抱歉，请问与国际服有关系吗?我可以装0.0.1.0没有test后缀的版本，但是0.0.1.1会有问题

**Comment by uiharuayako** [comment]
那肯定有关系，但是你没log我无法判断问题
